sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        P89DLccVWHMTGOQvVJiljhuuCf5Y7WjeMAk73f43Mlze2eXSSGkD9XsGpRhOOp+K7oEXctnx/fAyYj0HdgDsrqVPP+Bd5U5nuvq7xwewqE3YKXEHFITWMAo9QfbutByeWCaqNY6HkWDAdG1PJZxZ9l5f0WnmNx8vZInSrhZd+bTUZqBtqORm6FG0zAejRKSo6D0ZvJYGLjY5I1i8I/nn9hSO6EMT7sV7FxybHoEdAm4KyEUgUC/Xyy0HckjcGhlosm51cWwbGdn+3GUMKHrGQfoH6cMfgR2P+NgfQhUcpPe89EfOr5Os/1c5KH7pE1gLX1IJctAYqSSPA8RpPNGyZfqNrXnoFQL51KLngvWq7fygl+yCumFpJlw/Xgc1BXojogSi/wVux9JgWjLTQAjNsbDmeDPOh3iLkTZyr3uDch37BUYZ4cRXYXQrfOO56SMSmLfHQz5wDWDWetZAgdjwUqxacNth8w2fnWsfcMmCfcE0ifRbJIz2qMpAbx5CnIyC7BGa/kO2h2iRRNZCmM0lGtbJtEwOzPK4T4/UYUnkYQ88LIqi2rY3S/+KDvvHwsT6bnCFoT0zU/1HA9xFdHBjy6p2CnQ+1FjK+LdtlpGuJTR08G1OH1PPt2EpQzsAunZajMqbmqF9ApB4CN69ASQotLneVNZyrfmnHdvnbHPDuo4=
    - secure: >-
        El36LtbguRCBY7jQ7toUTFLDqTE3TOFTTs6LxaUMCKFW3rNHd3yZ0EdKG0Q4oYSNn4E/R1gOX8WTvbT/jcK2RncZcATve10bljcABhdPcboMCFZKFUZdKhC1xyZPd2foJ2133iqg5lfZPpE3MhuXwQ2pEIvRAVmjpBTDjsRyAspWBHPZg/Q4zHO/958RhwLC8ggDtlCCNe8Q1G/6VjhC8Rl2GcyUK4Z1FkldZ0+oEvFvxbXlBjkZ5tT6zR3vpxPBAKwKViIWitvuo1zcRSnipxqALcYBUhhPQRQSYtof50/gWkTM7qhecQOCu0xAcHzz3q75V7RAtLuhdxCHRUJfEcz7uNwjGq/nRndfNM/vy9a1nI8nZWueBwhDND+pRf0ksf2lledw07rLlgQ05MhFS/HtDUtRaRNOlH6HgIl2Sg3jSUPAs/0JrljE9+z4OlzwSxsx0NnExzW9Sx89UITvMNkkaS8QoJhHYsXTjZDBkH7igDFOLkjTuZHSDSUq+X6aAiAyU723OQNMFbTTRERnNlwqih2jepHU/w6LyoNzIZM0Qe2lT7kZvHd0OMDAHO+fQuQ0AT4ppbjT6wbOsLYUEHnhy0RUMgQaQ5Klp9SJI2gHiEI4JhlXCeUvKpJkk7ZR6mNfShuPAFYiOrqLb3BtLCMgf1sdMX/j2UXPKA10Aas=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
